[package]
# Semantic Versioning is used: https://semver.org/
version = "0.5.2"

# Description
title =  "UW Lab Assets"
description="Extension containing configuration instances of different assets and sensors"
readme  = "docs/README.md"
repository = "https://github.com/UW-Lab/UWLab"
category = "robotics"
keywords = ["isaaclab", "robotics", "rl", "il", "learning"]

[dependencies]
"uwlab" = {}

# Main python module this extension provides.
[[python.module]]
name = "uwlab_assets"
